### ISSUE TITLE
The field `bezeichnung` in the JSON string is not defined in the `SmallMeldebereichDto` properties

### ISSUE THREAD

**Issue by crux** [Intensivregister/intensivregister-meldungsvalidierung#23]
moin, wahrscheinlich bin ich hier kaum richtig, aber wo sonst könnte man das fragen?

Wenn ich gegen die uat schnittstelle vom divi, mit dem aus der openapi spec generierten client eine meldung poste, dann bekomme ich eine server response die zu einem json serialisierungs fehler im generierten client führt.

Fehler im client: _The field `bezeichnung` in the JSON string is not defined in the `SmallMeldebereichDto` properties_:
```
java.lang.IllegalArgumentException: The field `bezeichnung` in the JSON string is not defined in the `SmallMeldebereichDto` properties. JSON: {"id":"bdad2461-43fc-4515-a17e-0da2fba744eb","bezeichnung":"Testmeldebereich Vertama","aktiv":true,"deaktivierungsGrund":null,"deaktivierungsDatum":null,"behandlungsschwerpunktL1":"ERWACHSENE","behandlungsschwerpunktL2":null}
```

Mein minimaler meldungs request im IDEA http client ({{variables}} are all well defined):

```
POST https://uat.intensivregister.de/api/meldungen
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "id": "{{$uuid}}",
  "meldebereich": {
    "id": "bdad2461-43fc-4515-a17e-0da2fba744eb"
  },
  "kapazitaeten": {
    "intensivBetten": 10,
    "intensivBettenBelegt": 7
  },
  "auspraegung": "V2"
}
```

UAT Server Response:
```
HTTP/1.1 200 
Date: Fri, 15 Dec 2023 13:32:46 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=0A27F4F48609E3804E4E3C4F3CF78744; Path=/api; Secure; HttpOnly
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Frame-Options: DENY

{
  "id": "581ae521-9fbe-45cc-9c9f-db0fa85fec41",
  "meldebereich": {
    "id": "bdad2461-43fc-4515-a17e-0da2fba744eb",
    "bezeichnung": "Testmeldebereich Vertama",
    "aktiv": true,
    "deaktivierungsGrund": null,
    "deaktivierungsDatum": null,
    "behandlungsschwerpunktL1": "ERWACHSENE",
    "behandlungsschwerpunktL2": null
  },
  "meldezeitpunkt": "2023-12-15T13:32:46.609909912Z",
  "faelleCovidAktuell": null,
  "faelleCovidAktuellBeatmet": null,
  "faelleCovidGenesen": null,
  "faelleCovidVerstorben": null,
  "faelleCovidAktuellHighFlowOxygen": null,
  "faelleCovidAktuellNichtInvasivBeatmet": null,
  "faelleCovidAktuellEcmo": null,
  "faelleCovidOhneSymptomatik": null,
  "faelleCovidAelterAls17j": null,
  "betriebssituation": null,
  "betriebseinschraenkungPersonal": null,
  "betriebseinschraenkungRaum": null,
  "betriebseinschraenkungBeatmungsgeraet": null,
  "betriebseinschraenkungVerbrauchsmaterial": null,
  "api_version": "1.0",
  "quellsystem": "ir-uat-thirdparty-vertama",
  "lastUpdateTimestamp": "2023-12-15T13:32:46.609909912Z",
  "lastUpdateIdmUserId": "678db46d-61cc-4ce4-b060-7fe87fff51df",
  "creationIdmUserId": "678db46d-61cc-4ce4-b060-7fe87fff51df",
  "creationTimestamp": "2023-12-15T13:32:46.609909912Z",
  "meldezeitpunktManuellGeaendertTimestamp": null,
  "aktiv": true,
  "kapazitaeten": {
    "intensivBetten": 10,
    "intensivBettenBelegt": 7,
    "patientenNichtInvasivBeatmet": null,
    "patientenInvasivBeatmet": null,
    "patientenEcmo": null,
    "freieIvKapazitaet": null,
    "freieEcmoKapazitaet": null,
    "intensivBettenNotfall7d": null,
    "statusEinschaetzungLowcare": null,
    "statusEinschaetzungHighcare": null,
    "statusEinschaetzungEcmo": null
  },
  "auspraegung": "V2",
  "altersstrata": null,
  "neuaufnahmen": null,
  "varianten": null,
  "schwangereCovidStatus": null,
  "impfstatus": null,
  "impfstatusV2": null,
  "rsvStatus": null,
  "influenzaStatus": null,
  "covid19StatusV3": null,
  "faelleCovidVortagVerlegtVerstorben": null
}
```

Wie man sieht wird der Meldungspost angenommen, aber der generierte client scheitert am response json bei:
```
...
"meldebereich": {
    "id": "bdad2461-43fc-4515-a17e-0da2fba744eb",
    "bezeichnung": "Testmeldebereich Vertama",
    "aktiv": true,
    "deaktivierungsGrund": null,
    "deaktivierungsDatum": null,
    "behandlungsschwerpunktL1": "ERWACHSENE",
    "behandlungsschwerpunktL2": null
  },
..
```

was nicht weiter verwunderlich ist, da im openapi spec (`https://uat.intensivregister.de/api/public/api-docs`) das response meldebereich object definiert ist wie folgt: 
```
...
"SmallMeldebereichDto": {
    "required": [
        "id"
    ],
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        }
    }
}...
```

So sieht das in der doku vom (von uns) generierten client aus:
--> https://github.com/Vertama-GmbH/divi-openapi-okhttp-gson-client/blob/main/client-doc-generated/docs/SubmitMeldungResponseDto.md --> https://github.com/Vertama-GmbH/divi-openapi-okhttp-gson-client/blob/main/client-doc-generated/docs/SmallMeldebereichDto.md

Diese zusätzlichen Felder, neben "id", sind im der response spezifikation nicht vorgesehen:  `bezeichnung, aktiv, deaktivierungsGrund, deaktivierungsDatum, behandlungsschwerpunktL1 und behandlungsschwerpunktL2`.

**Comment by fanalin** [comment]
Guten Tag,

diese Felder sind im eigentlichen Objekt enthalten, und werden nur in der Spec ausgeblendet (da wir diese nicht zum Teil der "offiziellen" API werden lassen wollen).
Bisher sind wir auch immer davon ausgegangen, dass API-Clients nach "ignore unknown" vorgehen (zztl Felder wie hier also ignoriert werden).
Vielleicht können Sie mal schauen, inwiefern das bei den von Ihnen eingesetzten OpenAPI-Generator ebenfalls möglich ist.

Parallel schaue ich nächste Woche, inwiefern wir SmallMeldebereichDto durch eine neue, angepasste Klasse ersetzen können. Dies ist ein eher älterer Code-Teil; damals haben wir eher versucht DTO-Klassen wiederzuverwenden. Aber irgendwann haben wir festgestellt dass dieser Ansatz nicht mehr gereicht hat (zuviele unterschiedliche Use-Cases) und verfolgen derzeit eher die Strategie, pro Use-Case (z.B. Request/Response für einen Endpunkt) separate DTOs zu erstellen (wie man an der Basisklasse SubmitMeldungRequest/SubmitMeldungResponse bereits sieht). Hier würde ich dann entsprechend das SmallMeldebereichDto durch eine andere Klasse ersetzen in der nur die am Ende gewünschten Felder enthalten sind.

Ich schaue, dass ich den Change am Montag mache.

**Comment by fanalin** [comment]
Zur internen Nachverfolgung: IR-2072

**Comment by crux** [comment]
top, damit kann ich was anfangen, ich gehe mal auf die Suche. wäre auch default von einem ignore unknown ausgegangen, vielleicht kann ich das ja auch noch finden m Generator.

**Comment by crux** [comment]
on further investigation, I find that it is NOT the json parsing what fails but some kind of model validation logic on that object in the generated client: 
```
if (!SmallMeldebereichDto.openapiFields.contains(entry.getKey())) {
    throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SmallMeldebereichDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
}
```

I will continue looking into, might be finding a way to include a 'correction' for that in the client generation options. 

```
java.lang.IllegalArgumentException: The field `bezeichnung` in the JSON string is not defined in the `SmallMeldebereichDto` properties. JSON: {"id":"bdad2461-43fc-4515-a17e-0da2fba744eb","bezeichnung":"Testmeldebereich Vertama","aktiv":true,"deaktivierungsGrund":null,"deaktivierungsDatum":null,"behandlungsschwerpunktL1":"ERWACHSENE","behandlungsschwerpunktL2":null}
	at de.vertama.divi.client.model.SmallMeldebereichDto.validateJsonElement(SmallMeldebereichDto.java:151)
	at de.vertama.divi.client.model.SubmitMeldungResponseDto.validateJsonElement(SubmitMeldungResponseDto.java:1333)
	at de.vertama.divi.client.model.SubmitMeldungResponseDto$CustomTypeAdapterFactory$1.read(SubmitMeldungResponseDto.java:1419)
	at de.vertama.divi.client.model.SubmitMeldungResponseDto$CustomTypeAdapterFactory$1.read(SubmitMeldungResponseDto.java:1409)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1186)
	at de.vertama.divi.client.invoker.JSON.deserialize(JSON.java:217)
	at de.vertama.divi.client.invoker.ApiClient.deserialize(ApiClient.java:911)
...
```

**Comment by crux** [comment]
okay, found it. It actually seems to relate what is considered a generator bug, choosing to keep a default setting which leads to incorrect code: https://github.com/OpenAPITools/openapi-generator/issues/12550#issuecomment-1152596082

From their docs:
"disallowAdditionalPropertiesIfNotPresent" -->  ...If true (default), keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default....

For what it's worth, this now is my generator line, including the crucial part, which is  `--additional-properties=disal
lowAdditionalPropertiesIfNotPresent=false`:

```
$ openapi-generator-cli generate    -i https://uat.intensivregister.de/api/public/api-docs    --api-package de.vertama.div
i.client.api    --model-package de.vertama.divi.client.model    --invoker-package de.vertama.divi.client.invoker    --group-id de.vertama    --artifact-id divi-openapi-client    --artifact-version 2023.12.17    --additional-properties=disal
lowAdditionalPropertiesIfNotPresent=false    -g java    -p java8=true    --library okhttp-gson    -o "build/openapi-gene
rator-cli-generated"       
$

submitting my minimal post to the UAT Api now works, including correct parsing of the response by the generated openapi client. 

I leave it up to you to close the issue as you like. Actually I consider it a good decision to have additional info in the response, without adding ot the official SmallMeldebereichDto. According to standard this also is totally valid would work out of the box, for valid clients.
